### ISSUE TITLE
On Debian, the end of the script doesn't succeed to source .zshrc

### ISSUE THREAD

**Issue by kud** [ohmyzsh/ohmyzsh#1315]
This is what I've got:

```
Looking for an existing zsh config...
Found ~/.zshrc. Backing up to ~/.zshrc.pre-oh-my-zsh
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
Time to change your default shell to zsh!
Password: chsh: PAM authentication failed
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/


 ....is now installed.
sh: 39: source: not found
```

I need to do `$ source .zshrc` manually in order to work correctly.

**Comment by yely** [comment]
from [this link](https://github.com/robbyrussell/oh-my-zsh/issues/1224) I found a solution from @ryaninhust:  

```
sudo vim /etc/pam.d/chsh
```

then, comment auth required pam_shells.so

```
sudo chsh $USER -s $(which zsh)
```

done, logout and login.

**Comment by AndrejMitrovic** [comment]
> robbyrussell closed this Mar 22, 2014

Really, you're just going to close the issue even though this happens on every single Ubuntu-based machine when installing OMZ from scratch?

**Comment by moeabdol** [comment]
Thank @NeuralSandwich  this solved the same issue on ArchLinux.

**Comment by mcornella** [comment]
@ghost can you open a new issue with your details? Separate people posted different problems here, and it's difficult to know what the actual issue is. 
The part about the `sh: 39: source: not found` error was solved by using `.` instead of `source`, though the script is still wrong because it should `exec` a new zsh instead of [calling it and then sourcing it](https://github.com/robbyrussell/oh-my-zsh/blob/3ea33841863c4f5f22a27e64ae7950d901b674af/tools/install.sh#L51-L52) like it's done now.

**Comment by smeagol91** [comment]
All the problems related to `^M` cames from git (in my case)
just try:
`git config --global core.autocrlf false`
And then install oh-my-zsh and be happy.
