### ISSUE TITLE
Backspace not working properly

### ISSUE THREAD

**Issue by faahiero** [ohmyzsh/ohmyzsh#9155]
After the last update that i did (yesterday), when i press Backspace key (only backspace, without another key), it deletes entire words, one word for each keystroke. Before update, BS delete only a single letter of a word. It a bug or a new funcionality?
Anyone can help me with this?

**Comment by msbundles** [comment]
I updated today, and am having the exact same issue. I have spent a few hours looking to see if it is a new feature with an option to turn it off, but I have not any mention of the change or an option for it.

**Comment by stevenxmy** [comment]
+1

**Comment by rhaamo** [comment]
Apparently commit e04564d starts to break things.
I have ```cd .oh-my-zsh && git checkout ec70c0c393e53004b885d146dd77b9a3f136971a``` until a fix lands in master.

**Comment by IanSmith123** [comment]
`cd .oh-my-zsh && git checkout ec70c0c393e53004b885d146dd77b9a3f136971a`
Thanks @rhaamo , this command works for me.

**Comment by mcornella** [comment]
Hi there, sorry for the trouble. Try running `bindkey '^H' backward-kill-char` to see if it fixes it, I pushed a change to support CTRL-Backspace which might conflict with normal Backspace behavior.

**Comment by rhaamo** [comment]
@mcornella that seems to fix it for me

**Comment by faahiero** [comment]
@mcornella Works like a charm! Thanks for the help

**Comment by faahiero** [comment]
@mcornella How to make this permanent? If i close the terminal and re-open, still the same.

**Comment by scratchmex** [comment]
For me `indkey -M emacs '^H' backward-kill-word` works ok, why is that?. At the beginning I just needed to reload my terminal to remove the word deletion via backspace
