### ISSUE TITLE
git-auto-fetch lags while get fetch is performed

### ISSUE THREAD

**Issue by avatar-lavventura** [ohmyzsh/ohmyzsh#9416]
Feature request is related to `ohmyzsh/plugins/git-auto-fetch/`. I observe that it makes terminal freeze for a second when fetching is performed.

Here https://github.com/ohmyzsh/ohmyzsh/blob/26df8a22741ea4bb5264233344e42ce900fd26b6/plugins/git-auto-fetch/git-auto-fetch.plugin.zsh#L9

`git fetch 2>/dev/null` operation is slow and makes terminal to halt or freeze for a second while its on process.

Instead following approach might help to remove the lag:

Using `(&>/dev/null git fetch &)` will let `git fetch` to run on the background and does not let terminal shell to be freeze for a second.

```bash
function git-fetch-all {
    (`command git rev-parse --is-inside-work-tree 2>/dev/null` &&
         dir=`command git rev-parse --git-dir` &&
         [[ ! -f $dir/NO_AUTO_FETCH ]] &&
         (( `date +%s` - `date -r $dir/FETCH_LOG +%s 2>/dev/null || echo 0` > $GIT_AUTO_FETCH_INTERVAL )) &&
         GIT_SSH_COMMAND="command ssh -o BatchMode=yes" command \
                        ~/git_zsh_fetch.sh )
}
```

`git_zsh_fetch.sh` :

```bash
#!/bin/bash

(&>/dev/null git fetch --all &)
(&>/dev/null git pull --rebase --autostash &)
```

**Comment by mcornella** [comment]
cc @slavaGanzin

**Comment by mcornella** [comment]
Are you sure that's git-auto-fetch? There is already a `&` in the `git fetch` command which should make it asynchronous. In fact I've tested it and it does. You can run `functions -t git-fetch-all` so that you get a trace when it is run, so you can correlate it to when you experience the freeze. If it indeed is `git-auto-fetch`'s fault, please post more about your setup (network setup, filesystem/hard drive type, anything you might think can help us reproduce the issue).

**Comment by mcornella** [comment]
Ok after more testing I've seen that the rest of the commands in the `git-fetch-all` function might be to blame, since they're not put in the background. A hackish solution is to put the whole function in the background, but because of zsh's job management we get multiple jobs in the current zsh session and are notified on creation/finish. So a more hackish solution is to put them in a second sub-shell, try this out and tell me if you experience any improvements:

```zsh
function git-fetch-all {
  (
    (
      set -e
      # Get git root directory
      local gitdir="$(command git rev-parse --git-dir 2>/dev/null)"
      # Do nothing if auto-fetch disabled
      [[ ! -f "$gitdir/NO_AUTO_FETCH" ]] || return 0
      # Get time in seconds when auto-fetch was last run
      local lastrun="$(date -r "$gitdir/FETCH_LOG" +%s 2>/dev/null || echo 0)"
      # Do nothing if not enough time has passed since last auto-fetch
      (( EPOCHSECONDS - lastrun > $GIT_AUTO_FETCH_INTERVAL )) || return 0
      # Run git fetch in the background
      GIT_SSH_COMMAND="command ssh -o BatchMode=yes" \
        command git fetch --all 2>/dev/null &>! "$gitdir/FETCH_LOG"
    ) &
  )
}
```

PS. I'm aware that this'll leave many jobs running in parallel, a better solution is to implement a proper async algorithm but I haven't learned the trick yet.

**Comment by avatar-lavventura** [comment]
@mcornella I have experience this in `Ubuntu` and `Mac`. Since I was in the git repo I was keep experiencing the lag.

=> In addition, in `git` sometimes I squash latest few commits using following [answer](https://stackoverflow.com/a/5201642/2402577).

> git reset --soft HEAD~3 && 
> git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"

or while `git push` was in process `git-auto-fetch` may take action.

During this operation, `git-auto-fetch` may take action right after `git reset --soft HEAD~3` and before `git commit`; which leads  `git` to stuck in the `rebase` operation. So I just does not allow `git-auto-fetch` during the `rebase` as well in the script.


---------------

My hackish solution as follows, I am not familiar with `.zsh` file, that's why I am calling a external script I am calling and basically I just use ` (&>/dev/null git fetch --all&)` instead of `git fetch --all &`.

git_zsh_fetch.sh

```
#!/bin/bash

output=$(ls `git rev-parse --git-dir` | grep rebase || echo "no_base")
if [[ "$output" == "no_base" ]];then
    num=$(ps aux | grep -E "[g]it push" | wc -l)  # check is "git push --force" is in
process or not
    if [ $num -eq 0 ]; then
        (&>/dev/null git fetch --all&)
        (&>/dev/null git pull --rebase --autostash &)
    fi
fi
```

=> I will try your updated code and I will let you know the results.

**Comment by mcornella** [comment]
Try this instead (you can just run it in the command prompt):
```zsh
function git-fetch-all {
  (
    set -e
    # Get git root directory
    local gitdir
    gitdir="$(command git rev-parse --git-dir 2>/dev/null)"
    # Do nothing if auto-fetch disabled
    [[ ! -f "$gitdir/NO_AUTO_FETCH" ]]
    # Get time in seconds when auto-fetch was last run
    local lastrun="$(zstat +mtime "$gitdir/FETCH_LOG" 2>/dev/null || echo 0)"
    # Do nothing if not enough time has passed since last auto-fetch
    (( EPOCHSECONDS - lastrun > $GIT_AUTO_FETCH_INTERVAL ))
    # Run git fetch in the background
    GIT_SSH_COMMAND="command ssh -o BatchMode=yes" \
      command git fetch --all 2>/dev/null &>! "$gitdir/FETCH_LOG"
  ) &|
}
```

`git fetch` doesn't rebase, it just fetches available objects. This is probably a result of you calling `git pull`. The only way `git-auto-fetch` could be harmful is if it run between you making a commit and running a `git push --force-with-lease`, so you'd get new commits you weren't aware of and therefore the `git push` would act as a `git push --force`.

**Comment by avatar-lavventura** [comment]
I am getting following message: `git-fetch-all:13: permission denied: /FETCH_LOG`

**Comment by mcornella** [comment]
In theory, the git command should return a failure code, and with `set -e` should make the subshell exit. What `zsh --version` and `git --version` are you running?

**Comment by avatar-lavventura** [comment]
```
zsh 5.7.1 (x86_64-ubuntu-linux-gnu)
❯ git --version
git version 2.20.1
```

----

In the startup root user runs a script using `crontab`; maybe during that root user may change the permission of the related file.

**Comment by mcornella** [comment]
I couldn't reproduce this but I just added the directory check as you suggested, just to be sure.

I pushed #9468, go ahead and try that with `omz pr test 9468` and let me know if you see any improvements.

**Comment by avatar-lavventura** [comment]
Ah now I am getting following message: `No such shell function `_git-auto-fetch-zle-line-init'`; after doing `omz pr test 9468`

**Comment by mcornella** [comment]
Dumb rename error, try now.

**Comment by avatar-lavventura** [comment]
I am still getting `git-fetch-all:12: permission denied: /FETCH_LOG` message but it may be something related on my end. I only have it when I am in the home directory

**Comment by mcornella** [comment]
What do you get when running `command git rev-parse --git-dir 2>/dev/null`?

**Comment by avatar-lavventura** [comment]
If its git repo I get `.git` if not:

```
❯ git rev-parse --git-dir 2>/dev/null
home ~ ❯ git-fetch-all:12: permission denied: /FETCH_LOG
```

**Comment by mcornella** [comment]
Are you sure you haven't redefined the `git-fetch-all` function somewhere, possibly when testing previously? What does `which git-fetch-all` say?

**Comment by avatar-lavventura** [comment]
`git-fetch-all` returns nothing. 

its defined on:

```
./plugins/git-auto-fetch/git-auto-fetch.plugin.zsh :4:# Necessary for the git-fetch-all function
./plugins/git-auto-fetch/git-auto-fetch.plugin.zsh :7:function git-fetch-all {
./plugins/git-auto-fetch/git-auto-fetch.plugin.zsh :43: git-fetch-all
./plugins/git-auto-fetch/git-auto-fetch.plugin.zsh :48: git-fetch-all
```

**Comment by mcornella** [comment]
You missed `which`, it's `which git-fetch-all`.

**Comment by avatar-lavventura** [comment]
Ah sorry:

```
$ which git-fetch-all
git-fetch-all () {
	(
		set -e
		gitdir="$(command git rev-parse --git-dir 2>/dev/null)"
		[[ -d "$gitdir" && ! -f "$gitdir/NO_AUTO_FETCH" ]]
		lastrun="$(zstat +mtime "$gitdir/FETCH_LOG" 2>/dev/null || echo 0)"
		(( EPOCHSECONDS - lastrun > $GIT_AUTO_FETCH_INTERVAL ))
		GIT_SSH_COMMAND="command ssh -o BatchMode=yes" command git fetch --all 2> /dev/null &>| "$gitdir/FETCH_LOG"
	) &|
}
```

**Comment by mcornella** [comment]
My mistake, hold on.

**Comment by mcornella** [comment]
> But when I do `source ~/.zshrc` the warning message is gone

Yeah because the `zle-line-init` function gets overwritten by OMZ's one, that's a separate bug.

The thing is, `set -e` is not working, so the condition should be returning. I don't understand why `set -e` doesn't work, so I'll post a few tests and you tell me the output:

```zsh
(set -e; false; echo 1; )
(set -e; false; echo 2; ) &|
() { (set -e; false; echo 3; ); }
() { (set -e; false; echo 4; ) &|; }
(setopt errexit; false; echo 5; )
(setopt errexit; false; echo 6; ) &|
() { (setopt errexit; false; echo 7; ); }
() { (setopt errexit; false; echo 8; ) &|; }
(set -o errexit; false; echo 9; )
(set -o errexit; false; echo 10; ) &|
() { (set -o errexit; false; echo 11; ); }
() { (set -o errexit; false; echo 12; ) &|; }
```

**Comment by avatar-lavventura** [comment]
Should I paste all into the terminal  ? When I paste each one-by-one they did not echo anything

**Comment by mcornella** [comment]
![](https://media.giphy.com/media/dn9QA6JiwOJws/source.gif)

I'm out of options, I think I'll just write it with ifs. Out of curiosity, what does `setopt` say?

**Comment by avatar-lavventura** [comment]
Fun gif :-)

---------

```
❯ setopt
alwaystoend
autocd
autopushd
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignorealldups
histignoredups
histignorespace
histnostore
histreduceblanks
histverify
ignoreeof
incappendhistory
interactive
interactivecomments
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
```

**Comment by mcornella** [comment]
I didn't get much from that. I think the problem is this, [documented in the zsh docs](http://zsh.sourceforge.net/Doc/Release/Options.html#index-ERREXIT):
> If a command has a non-zero exit status, execute the ZERR trap, if set, and exit. **This is disabled while running initialization scripts.**

I pushed an alternative version that uses proper ifs, try it out again with `omz pr test 9468`.

**Comment by mcornella** [comment]
Nevermind, I found [`err_return`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-ERRRETURN) which does a similar thing. Try it out now.

**Comment by avatar-lavventura** [comment]
@mcornella Thanks mate. I try it and seems like it works fine

**Comment by avatar-lavventura** [comment]
@mcornella not sure bit git-repo remains as ` master ⇡1 ⇣1 ` and `git pull -f` is not performed with the latest setup.

**Comment by avatar-lavventura** [comment]
@mcornella  How can I apply `git pull --rebase --autostash` right after `git fetch --all` is done ?
